const actionTypes = {
    EXAMPLE_ACTION: 'EXAMPLE_ACTION',
    EXAMPLE_ACTION_IN_PROGRESS: 'EXAMPLE_ACTION_IN_PROGRESS',
    EXAMPLE_ACTION_SUCCESS: 'EXAMPLE_ACTION_SUCCESS',
    EXAMPLE_ACTION_FAILED: 'EXAMPLE_ACTION_FAILED',
};

export default Object.freeze(actionTypes);
